import { query } from "../config/db.js";
import { cleanString, isValidEmail, isValidUrl, positiveInt } from "../utils.js";

export async function publicFaqs(req,res,next){try{const r=await query(`SELECT id,question_en,answer_en,question_am,answer_am,sort_order FROM faqs WHERE is_published=TRUE ORDER BY sort_order,id`);res.json({success:true,items:r.rows})}catch(e){next(e)}}
export async function adminFaqs(req,res,next){try{const r=await query(`SELECT * FROM faqs ORDER BY sort_order,id`);res.json({success:true,items:r.rows})}catch(e){next(e)}}
export async function createFaq(req,res,next){try{const b=req.body||{};const q=cleanString(b.questionEn,1000),a=cleanString(b.answerEn,10000);if(!q||!a)return res.status(400).json({success:false,message:"English question and answer are required."});const r=await query(`INSERT INTO faqs(question_en,answer_en,question_am,answer_am,is_published,sort_order) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[q,a,cleanString(b.questionAm,1000)||null,cleanString(b.answerAm,10000)||null,Boolean(b.isPublished),positiveInt(b.sortOrder)]);res.status(201).json({success:true,item:r.rows[0]})}catch(e){next(e)}}
export async function updateFaq(req,res,next){try{const b=req.body||{};const r=await query(`UPDATE faqs SET question_en=COALESCE(NULLIF($1,''),question_en),answer_en=COALESCE(NULLIF($2,''),answer_en),question_am=NULLIF($3,''),answer_am=NULLIF($4,''),is_published=COALESCE($5,is_published),sort_order=COALESCE($6,sort_order),updated_at=NOW() WHERE id=$7 RETURNING *`,[cleanString(b.questionEn,1000),cleanString(b.answerEn,10000),cleanString(b.questionAm,1000),cleanString(b.answerAm,10000),typeof b.isPublished==="boolean"?b.isPublished:null,b.sortOrder===undefined?null:positiveInt(b.sortOrder),req.params.id]);if(!r.rowCount)return res.status(404).json({success:false,message:"FAQ not found."});res.json({success:true,item:r.rows[0]})}catch(e){next(e)}}
export async function deleteFaq(req,res,next){try{const r=await query("DELETE FROM faqs WHERE id=$1 RETURNING id",[req.params.id]);if(!r.rowCount)return res.status(404).json({success:false,message:"FAQ not found."});res.json({success:true})}catch(e){next(e)}}

export async function publicVacancies(req,res,next){try{const r=await query(`SELECT id,title_en,title_am,description_en,description_am,requirements_en,requirements_am,location,employment_type,closing_date FROM job_vacancies WHERE status='OPEN' AND (closing_date IS NULL OR closing_date>=CURRENT_DATE) ORDER BY closing_date NULLS LAST,created_at DESC`);res.json({success:true,items:r.rows})}catch(e){next(e)}}
export async function adminVacancies(req,res,next){try{const r=await query("SELECT * FROM job_vacancies ORDER BY created_at DESC");res.json({success:true,items:r.rows})}catch(e){next(e)}}
export async function createVacancy(req,res,next){try{const b=req.body||{},title=cleanString(b.titleEn,255);if(!title)return res.status(400).json({success:false,message:"English job title is required."});const r=await query(`INSERT INTO job_vacancies(title_en,title_am,description_en,description_am,requirements_en,requirements_am,location,employment_type,closing_date,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[title,cleanString(b.titleAm,255)||null,cleanString(b.descriptionEn,20000)||null,cleanString(b.descriptionAm,20000)||null,cleanString(b.requirementsEn,20000)||null,cleanString(b.requirementsAm,20000)||null,cleanString(b.location,255)||null,cleanString(b.employmentType,100)||null,b.closingDate||null,b.status==="CLOSED"?"CLOSED":"OPEN"]);res.status(201).json({success:true,item:r.rows[0]})}catch(e){next(e)}}
export async function deleteVacancy(req,res,next){try{const r=await query("DELETE FROM job_vacancies WHERE id=$1 RETURNING id",[req.params.id]);if(!r.rowCount)return res.status(404).json({success:false,message:"Vacancy not found."});res.json({success:true})}catch(e){next(e)}}

export async function updateVacancy(req,res,next){try{const b=req.body||{};const r=await query(`UPDATE job_vacancies SET title_en=COALESCE(NULLIF($1,''),title_en),title_am=NULLIF($2,''),description_en=NULLIF($3,''),description_am=NULLIF($4,''),requirements_en=NULLIF($5,''),requirements_am=NULLIF($6,''),location=NULLIF($7,''),employment_type=NULLIF($8,''),closing_date=$9,status=COALESCE(NULLIF($10,''),status),updated_at=NOW() WHERE id=$11 RETURNING *`,[cleanString(b.titleEn,255),cleanString(b.titleAm,255),cleanString(b.descriptionEn,20000),cleanString(b.descriptionAm,20000),cleanString(b.requirementsEn,20000),cleanString(b.requirementsAm,20000),cleanString(b.location,255),cleanString(b.employmentType,100),b.closingDate||null,b.status,req.params.id]);if(!r.rowCount)return res.status(404).json({success:false,message:"Vacancy not found."});res.json({success:true,item:r.rows[0]})}catch(e){next(e)}}

export async function publicAlbums(req,res,next){try{const albums=await query(`SELECT a.*,COALESCE(json_agg(json_build_object('id',i.id,'title_en',i.title_en,'title_am',i.title_am,'image_url',i.image_url,'sort_order',i.sort_order) ORDER BY i.sort_order,i.id) FILTER (WHERE i.id IS NOT NULL),'[]') AS photos FROM gallery_albums a LEFT JOIN gallery_items i ON i.album_id=a.id WHERE a.is_published=TRUE GROUP BY a.id ORDER BY a.event_date DESC NULLS LAST,a.created_at DESC`);res.json({success:true,items:albums.rows})}catch(e){next(e)}}
export async function adminAlbums(req,res,next){try{const r=await query(`SELECT a.*,COUNT(i.id)::int AS photo_count FROM gallery_albums a LEFT JOIN gallery_items i ON i.album_id=a.id GROUP BY a.id ORDER BY a.event_date DESC NULLS LAST,a.created_at DESC`);res.json({success:true,items:r.rows})}catch(e){next(e)}}
export async function createAlbum(req,res,next){try{const b=req.body||{},title=cleanString(b.titleEn,255);if(!title)return res.status(400).json({success:false,message:"English album title is required."});const r=await query(`INSERT INTO gallery_albums(title_en,title_am,description_en,description_am,is_published,event_date) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[title,cleanString(b.titleAm,255)||null,cleanString(b.descriptionEn,10000)||null,cleanString(b.descriptionAm,10000)||null,Boolean(b.isPublished),b.eventDate||null]);res.status(201).json({success:true,item:r.rows[0]})}catch(e){next(e)}}
export async function updateAlbum(req,res,next){try{const b=req.body||{};const r=await query(`UPDATE gallery_albums SET title_en=COALESCE(NULLIF($1,''),title_en),title_am=NULLIF($2,''),description_en=NULLIF($3,''),description_am=NULLIF($4,''),is_published=COALESCE($5,is_published),event_date=$6,updated_at=NOW() WHERE id=$7 RETURNING *`,[cleanString(b.titleEn,255),cleanString(b.titleAm,255),cleanString(b.descriptionEn,10000),cleanString(b.descriptionAm,10000),typeof b.isPublished==="boolean"?b.isPublished:null,b.eventDate||null,req.params.id]);if(!r.rowCount)return res.status(404).json({success:false,message:"Album not found."});res.json({success:true,item:r.rows[0]})}catch(e){next(e)}}

export async function publicSettings(req,res,next){try{const r=await query("SELECT setting_key,setting_value FROM site_settings");res.json({success:true,settings:Object.fromEntries(r.rows.map(x=>[x.setting_key,x.setting_value||""]))})}catch(e){next(e)}}
export async function adminSettings(req,res,next){try{const r=await query("SELECT setting_key,setting_value FROM site_settings ORDER BY setting_key");res.json({success:true,settings:Object.fromEntries(r.rows.map(x=>[x.setting_key,x.setting_value||""]))})}catch(e){next(e)}}
export async function updateSettings(req,res,next){try{const allowed=["organization_email","facebook_url","telegram_url","linkedin_url","youtube_url"];const b=req.body||{};for(const key of allowed){if(b[key]!==undefined){const value=cleanString(b[key],1000);if(key==="organization_email"&&value&&!isValidEmail(value))return res.status(400).json({success:false,message:"Invalid organizational email."});if(key.endsWith("_url")&&value&&!isValidUrl(value))return res.status(400).json({success:false,message:`Invalid URL for ${key}.`});await query(`INSERT INTO site_settings(setting_key,setting_value) VALUES($1,$2) ON CONFLICT(setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,updated_at=NOW()`,[key,value])}}res.json({success:true})}catch(e){next(e)}}

export async function listApplications(req,res,next){try{const status=["PENDING","REVIEW","APPROVED","REJECTED"].includes(req.query.status)?req.query.status:null;const r=await query(`SELECT m.*,CASE WHEN m.submitted_at IS NULL THEN NULL ELSE 'ETEF-'||EXTRACT(YEAR FROM m.submitted_at)::int||'-'||RIGHT(REPLACE(m.id::text,'-',''),6) END AS reference FROM membership_applications m ${status?"WHERE status=$1":""} ORDER BY submitted_at DESC LIMIT 100`,status?[status]:[]);res.json({success:true,items:r.rows})}catch(e){next(e)}}
export async function applicationStats(req,res,next){try{const r=await query(`SELECT COUNT(*)::int AS total,COUNT(*) FILTER(WHERE status='PENDING')::int AS pending,COUNT(*) FILTER(WHERE status='REVIEW')::int AS review,COUNT(*) FILTER(WHERE status='APPROVED')::int AS approved,COUNT(*) FILTER(WHERE status='REJECTED')::int AS rejected FROM membership_applications`);res.json({success:true,stats:r.rows[0]})}catch(e){next(e)}}
export async function updateApplication(req,res,next){try{const status=String(req.body?.status||"").toUpperCase();if(!["PENDING","REVIEW","APPROVED","REJECTED"].includes(status))return res.status(400).json({success:false,message:"Invalid application status."});const r=await query(`UPDATE membership_applications SET status=$1,reviewed_at=NOW(),reviewed_by=$2 WHERE id=$3 RETURNING *`,[status,req.admin.id,req.params.id]);if(!r.rowCount)return res.status(404).json({success:false,message:"Application not found."});res.json({success:true,item:r.rows[0]})}catch(e){next(e)}}

export async function submitMembership(req,res,next){try{const b=req.body||{};const required=["organizationName","organizationType","sector","region","city","address","members","vehicles","manager","managerPhone","email"];for(const k of required)if(!cleanString(b[k]))return res.status(400).json({success:false,message:`${k} is required.`});if(!isValidEmail(cleanString(b.email)))return res.status(400).json({success:false,message:"Valid organization email is required."});const r=await query(`INSERT INTO membership_applications(organization_name,organization_type,transport_sector,region,city,sub_city,woreda,office_address,phone,email,member_count,vehicle_count,general_manager_name,general_manager_phone,general_manager_email,federation_representative_name,federation_representative_phone) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) RETURNING id,submitted_at`,[cleanString(b.organizationName,255),cleanString(b.organizationType,100),cleanString(b.sector,100),cleanString(b.region,120),cleanString(b.city,120),cleanString(b.subCity,120)||null,cleanString(b.woreda,120)||null,cleanString(b.address,5000),cleanString(b.phone,50)||null,cleanString(b.email,255),positiveInt(b.members),positiveInt(b.vehicles),cleanString(b.manager,180),cleanString(b.managerPhone,50),cleanString(b.managerEmail,255)||null,cleanString(b.representative,180)||null,cleanString(b.representativePhone,50)||null]);const row=r.rows[0];const reference=`ETEF-${new Date(row.submitted_at).getFullYear()}-${row.id.replaceAll("-","").slice(-6).toUpperCase()}`;res.status(201).json({success:true,reference,id:row.id,submittedAt:row.submitted_at})}catch(e){next(e)}}

export async function publicContent(req,res,next){
  try {
    const r=await query(`SELECT content_key,title_en,title_am,body_en,body_am FROM site_content WHERE is_published=TRUE ORDER BY content_key`);
    res.json({success:true,items:r.rows});
  } catch(e){next(e)}
}

export async function adminContent(req,res,next){
  try {
    const r=await query(`SELECT * FROM site_content ORDER BY content_key`);
    res.json({success:true,items:r.rows});
  } catch(e){next(e)}
}

export async function updateContent(req,res,next){
  try {
    const allowed=new Set(["about","vision","mission"]);
    const key=String(req.params.key||"").toLowerCase();
    if(!allowed.has(key)) return res.status(404).json({success:false,message:"Content item not found."});
    const b=req.body||{};
    const titleEn=cleanString(b.titleEn,500), bodyEn=cleanString(b.bodyEn,30000);
    if(!titleEn||!bodyEn) return res.status(400).json({success:false,message:"English title and body are required."});
    const r=await query(`UPDATE site_content SET title_en=$1,title_am=$2,body_en=$3,body_am=$4,is_published=COALESCE($5,is_published),updated_at=NOW(),updated_by=$6 WHERE content_key=$7 RETURNING *`,[
      titleEn,cleanString(b.titleAm,500)||null,bodyEn,cleanString(b.bodyAm,30000)||null,typeof b.isPublished==="boolean"?b.isPublished:null,req.admin.id,key
    ]);
    if(!r.rowCount) return res.status(404).json({success:false,message:"Content item not found."});
    res.json({success:true,item:r.rows[0]});
  } catch(e){next(e)}
}

export async function publicNews(req,res,next){try{const r=await query(`SELECT id,title_en,title_am,excerpt_en,excerpt_am,body_en,body_am,image_url,published_at FROM news_posts WHERE is_published=TRUE ORDER BY published_at DESC NULLS LAST,created_at DESC`);res.json({success:true,items:r.rows})}catch(e){next(e)}}
export async function adminNews(req,res,next){try{const r=await query(`SELECT * FROM news_posts ORDER BY created_at DESC`);res.json({success:true,items:r.rows})}catch(e){next(e)}}
export async function createNews(req,res,next){try{const b=req.body||{},title=cleanString(b.titleEn,255);if(!title)return res.status(400).json({success:false,message:"English news title is required."});const published=Boolean(b.isPublished);const r=await query(`INSERT INTO news_posts(title_en,title_am,excerpt_en,excerpt_am,body_en,body_am,is_published,published_at,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[title,cleanString(b.titleAm,255)||null,cleanString(b.excerptEn,2000)||null,cleanString(b.excerptAm,2000)||null,cleanString(b.bodyEn,30000)||null,cleanString(b.bodyAm,30000)||null,published,published?new Date():null,req.admin.id]);res.status(201).json({success:true,item:r.rows[0]})}catch(e){next(e)}}
export async function updateNews(req,res,next){try{const b=req.body||{},published=typeof b.isPublished==='boolean'?b.isPublished:null;const r=await query(`UPDATE news_posts SET title_en=COALESCE(NULLIF($1,''),title_en),title_am=NULLIF($2,''),excerpt_en=NULLIF($3,''),excerpt_am=NULLIF($4,''),body_en=NULLIF($5,''),body_am=NULLIF($6,''),is_published=COALESCE($7,is_published),published_at=CASE WHEN $7=TRUE AND published_at IS NULL THEN NOW() WHEN $7=FALSE THEN NULL ELSE published_at END,updated_at=NOW(),updated_by=$8 WHERE id=$9 RETURNING *`,[cleanString(b.titleEn,255),cleanString(b.titleAm,255),cleanString(b.excerptEn,2000),cleanString(b.excerptAm,2000),cleanString(b.bodyEn,30000),cleanString(b.bodyAm,30000),published,req.admin.id,req.params.id]);if(!r.rowCount)return res.status(404).json({success:false,message:'News post not found.'});res.json({success:true,item:r.rows[0]})}catch(e){next(e)}}
export async function deleteNews(req,res,next){try{const r=await query('DELETE FROM news_posts WHERE id=$1 RETURNING id',[req.params.id]);if(!r.rowCount)return res.status(404).json({success:false,message:'News post not found.'});res.json({success:true})}catch(e){next(e)}}
